const ExpModel = [
	{
		cover:'assets/sketchCoverParticles.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/selfshadingParticles/dist/index.html',
		opened:false
	},
	{
		cover:'assets/sketchCoverReflection.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/reflectiveSoundVis/dist/index.html',
		opened:false
	},
	{
		cover:'assets/sketchCoverNefertiti.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/Nefertiti/dist/index.html',
		opened:false
	},
	{
		cover:'assets/sketchCoverFlocking.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/flockingBW/dist/index.html',
		opened:false
	},
	{
		cover:'assets/sketchCoverRosetta.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/rosetta/dist/index.html',
		opened:false
	},
	{
		cover:'assets/coverSketchNike.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/Bloom/dist/index.html',
		opened:false
	},
	{
		cover:'assets/coverSketchBloom.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/feathers/dist/index.html',
		opened:false
	},
	{
		cover:'assets/coverSketchClustering.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/flocking01/dist/index.html',
		opened:false
	},
	{
		cover:'assets/coverSketchRefraction.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/Refaction/dist/index.html',
		opened:false
	},
	{
		cover:'assets/textureProj.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/mask/dist/index.html',
		opened:false
	},
	{
		cover:'assets/costume.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/wrap/dist/index.html',
		opened:false
	},
	{
		cover:'assets/seasons.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/blossom/dist/index.html',
		opened:false
	},
	{
		cover:'assets/river.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/River/dist/index.html',
		opened:false
	}
]




export default ExpModel;