export default {
  TEXTURE_SIZE: 32,
  DENSITY_DISSIPATION: 0.994,
  VELOCITY_DISSIPATION: 0.996,
  PRESSURE_DISSIPATION: 0.996,
  PRESSURE_ITERATIONS: 20,
  CURL: 5,
  ADVECTION_SCALE: 1,
} as const;

export type FluidSettings = {
  TEXTURE_SIZE: number;
  DENSITY_DISSIPATION: number;
  VELOCITY_DISSIPATION: number;
  PRESSURE_DISSIPATION: number;
  PRESSURE_ITERATIONS: number;
  CURL: number;
  ADVECTION_SCALE: number;
};
