const ExpModel = [
	{
		cover:'assets/img/sketchCoverParticles.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/selfshadingParticles/dist/index.html',
		opened:false
	},
	{
		cover:'assets/img/sketchCoverReflection.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/reflectiveSoundVis/dist/index.html',
		opened:false
	},
	{
		cover:'assets/img/sketchCoverNefertiti.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/Nefertiti1/dist/index.html',
		opened:false
	},
	{
		cover:'assets/img/sketchCoverFlocking.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/flockingBW/dist/index.html',
		opened:false
	},
	{
		cover:'assets/img/sketchCoverRosetta.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/rosetta/dist/index.html',
		opened:false
	},
	{
		cover:'assets/img/coverSketchNike.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/Bloom/dist/index.html',
		opened:false
	},
	{
		cover:'assets/img/coverSketchBloom.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/feathers/dist/index.html',
		opened:false
	},
	{
		cover:'assets/img/coverSketchClustering.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/flocking01/dist/index.html',
		opened:false
	},
	{
		cover:'assets/img/coverSketchRefraction.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/Refaction/dist/index.html',
		opened:false
	},
	{
		cover:'assets/img/textureProj.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/mask/dist/index.html',
		opened:false
	},
	{
		cover:'assets/img/costume.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/wrap/dist/index.html',
		opened:false
	},
	{
		cover:'assets/img/seasons.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/blossom/dist/index.html',
		opened:false
	},
	{
		cover:'assets/img/river.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/River/dist/index.html',
		opened:false
	},
	{
		cover:'assets/img/coverSketchCrystal.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/nike/dist/index.html',
		opened:false
	},
	{
		cover:'assets/img/coverSketchSoundVisCircles.jpg',
		url:'http://www.bongiovi.tw/projects/soundVis/05/',
		opened:false
	},
	{
		cover:'assets/img/coverSketchSoundVisWaves.jpg',
		url:'http://www.bongiovi.tw/projects/soundVis/07/',
		opened:false
	},
	{
		cover:'assets/img/sketchCoverFogMountain.jpg',
		url:'http://www.bongiovi.tw/projects/kuafu/mountains/01/',
		opened:false
	},
	{
		cover:'assets/img/sketchCoverDandelion.jpg',
		url:'http://www.bongiovi.tw/projects/leap/02/',
		opened:false
	},
	{
		cover:'assets/img/coverSketchParticleValley.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/particlesValley/dist/index.html',
		opened:false
	},
	{
		cover:'assets/img/coverSketchBubbles.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/particles03/dist/index.html',
		opened:false
	},
	{
		cover:'assets/img/coverSketchTurbulence.jpg',
		url:'http://yiwenl.github.io/Sketches/experiments/turbulence/dist/index.html',
		opened:false
	}
]

module.exports = ExpModel;
// export default ExpModel;